/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as AppCoachesRouteImport } from './routes/app/coaches'
import { Route as AppUsersRouteImport } from './routes/app/users'
import { Route as AppWorkshopsIndexRouteImport } from './routes/app/workshops.index'
import { Route as AppWorkshopsNewRouteImport } from './routes/app/workshops.new'
import { Route as AppWorkshopsIdEditRouteImport } from './routes/app/workshops.$id.edit'
import { Route as AppWorkshopsIdManageRouteImport } from './routes/app/workshops.$id.manage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoachesRoute = AppCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkshopsIndexRoute = AppWorkshopsIndexRouteImport.update({
  id: '/workshops/',
  path: '/workshops/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkshopsNewRoute = AppWorkshopsNewRouteImport.update({
  id: '/workshops/new',
  path: '/workshops/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkshopsIdEditRoute = AppWorkshopsIdEditRouteImport.update({
  id: '/workshops/$id/edit',
  path: '/workshops/$id/edit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkshopsIdManageRoute = AppWorkshopsIdManageRouteImport.update({
  id: '/workshops/$id/manage',
  path: '/workshops/$id/manage',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/app/coaches': typeof AppCoachesRoute
  '/app/users': typeof AppUsersRoute
  '/app/workshops/new': typeof AppWorkshopsNewRoute
  '/app/workshops/': typeof AppWorkshopsIndexRoute
  '/app/workshops/$id/edit': typeof AppWorkshopsIdEditRoute
  '/app/workshops/$id/manage': typeof AppWorkshopsIdManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/app/coaches': typeof AppCoachesRoute
  '/app/users': typeof AppUsersRoute
  '/app/workshops/new': typeof AppWorkshopsNewRoute
  '/app/workshops': typeof AppWorkshopsIndexRoute
  '/app/workshops/$id/edit': typeof AppWorkshopsIdEditRoute
  '/app/workshops/$id/manage': typeof AppWorkshopsIdManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/app/coaches': typeof AppCoachesRoute
  '/app/users': typeof AppUsersRoute
  '/app/workshops/new': typeof AppWorkshopsNewRoute
  '/app/workshops/': typeof AppWorkshopsIndexRoute
  '/app/workshops/$id/edit': typeof AppWorkshopsIdEditRoute
  '/app/workshops/$id/manage': typeof AppWorkshopsIdManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/app/coaches'
    | '/app/users'
    | '/app/workshops/new'
    | '/app/workshops/'
    | '/app/workshops/$id/edit'
    | '/app/workshops/$id/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/app/coaches'
    | '/app/users'
    | '/app/workshops/new'
    | '/app/workshops'
    | '/app/workshops/$id/edit'
    | '/app/workshops/$id/manage'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/app/coaches'
    | '/app/users'
    | '/app/workshops/new'
    | '/app/workshops/'
    | '/app/workshops/$id/edit'
    | '/app/workshops/$id/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/coaches': {
      id: '/app/coaches'
      path: '/coaches'
      fullPath: '/app/coaches'
      preLoaderRoute: typeof AppCoachesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workshops/': {
      id: '/app/workshops/'
      path: '/workshops'
      fullPath: '/app/workshops/'
      preLoaderRoute: typeof AppWorkshopsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workshops/new': {
      id: '/app/workshops/new'
      path: '/workshops/new'
      fullPath: '/app/workshops/new'
      preLoaderRoute: typeof AppWorkshopsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workshops/$id/edit': {
      id: '/app/workshops/$id/edit'
      path: '/workshops/$id/edit'
      fullPath: '/app/workshops/$id/edit'
      preLoaderRoute: typeof AppWorkshopsIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workshops/$id/manage': {
      id: '/app/workshops/$id/manage'
      path: '/workshops/$id/manage'
      fullPath: '/app/workshops/$id/manage'
      preLoaderRoute: typeof AppWorkshopsIdManageRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppCoachesRoute: typeof AppCoachesRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWorkshopsNewRoute: typeof AppWorkshopsNewRoute
  AppWorkshopsIndexRoute: typeof AppWorkshopsIndexRoute
  AppWorkshopsIdEditRoute: typeof AppWorkshopsIdEditRoute
  AppWorkshopsIdManageRoute: typeof AppWorkshopsIdManageRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCoachesRoute: AppCoachesRoute,
  AppUsersRoute: AppUsersRoute,
  AppWorkshopsNewRoute: AppWorkshopsNewRoute,
  AppWorkshopsIndexRoute: AppWorkshopsIndexRoute,
  AppWorkshopsIdEditRoute: AppWorkshopsIdEditRoute,
  AppWorkshopsIdManageRoute: AppWorkshopsIdManageRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
