/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as AuthenticatedCoachesRouteImport } from './routes/_authenticated/coaches'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedWalkthroughsRouteImport } from './routes/_authenticated/walkthroughs'
import { Route as AuthenticatedWorkshopsIndexRouteImport } from './routes/_authenticated/workshops.index'
import { Route as AuthenticatedWorkshopsNewRouteImport } from './routes/_authenticated/workshops.new'
import { Route as WorkshopsIdBigScreenRouteImport } from './routes/workshops.$id.big-screen'
import { Route as AuthenticatedWorkshopsIdEditRouteImport } from './routes/_authenticated/workshops.$id.edit'
import { Route as AuthenticatedWorkshopsIdManageRouteImport } from './routes/_authenticated/workshops.$id.manage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoachesRoute = AuthenticatedCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalkthroughsRoute =
  AuthenticatedWalkthroughsRouteImport.update({
    id: '/walkthroughs',
    path: '/walkthroughs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkshopsIndexRoute =
  AuthenticatedWorkshopsIndexRouteImport.update({
    id: '/workshops/',
    path: '/workshops/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkshopsNewRoute =
  AuthenticatedWorkshopsNewRouteImport.update({
    id: '/workshops/new',
    path: '/workshops/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const WorkshopsIdBigScreenRoute = WorkshopsIdBigScreenRouteImport.update({
  id: '/workshops/$id/big-screen',
  path: '/workshops/$id/big-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkshopsIdEditRoute =
  AuthenticatedWorkshopsIdEditRouteImport.update({
    id: '/workshops/$id/edit',
    path: '/workshops/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkshopsIdManageRoute =
  AuthenticatedWorkshopsIdManageRouteImport.update({
    id: '/workshops/$id/manage',
    path: '/workshops/$id/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/coaches': typeof AuthenticatedCoachesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/walkthroughs': typeof AuthenticatedWalkthroughsRoute
  '/workshops/new': typeof AuthenticatedWorkshopsNewRoute
  '/workshops/$id/big-screen': typeof WorkshopsIdBigScreenRoute
  '/workshops/': typeof AuthenticatedWorkshopsIndexRoute
  '/workshops/$id/edit': typeof AuthenticatedWorkshopsIdEditRoute
  '/workshops/$id/manage': typeof AuthenticatedWorkshopsIdManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/coaches': typeof AuthenticatedCoachesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/walkthroughs': typeof AuthenticatedWalkthroughsRoute
  '/workshops/new': typeof AuthenticatedWorkshopsNewRoute
  '/workshops/$id/big-screen': typeof WorkshopsIdBigScreenRoute
  '/workshops': typeof AuthenticatedWorkshopsIndexRoute
  '/workshops/$id/edit': typeof AuthenticatedWorkshopsIdEditRoute
  '/workshops/$id/manage': typeof AuthenticatedWorkshopsIdManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/_authenticated/coaches': typeof AuthenticatedCoachesRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/walkthroughs': typeof AuthenticatedWalkthroughsRoute
  '/_authenticated/workshops/new': typeof AuthenticatedWorkshopsNewRoute
  '/workshops/$id/big-screen': typeof WorkshopsIdBigScreenRoute
  '/_authenticated/workshops/': typeof AuthenticatedWorkshopsIndexRoute
  '/_authenticated/workshops/$id/edit': typeof AuthenticatedWorkshopsIdEditRoute
  '/_authenticated/workshops/$id/manage': typeof AuthenticatedWorkshopsIdManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/coaches'
    | '/users'
    | '/walkthroughs'
    | '/workshops/new'
    | '/workshops/$id/big-screen'
    | '/workshops/'
    | '/workshops/$id/edit'
    | '/workshops/$id/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/coaches'
    | '/users'
    | '/walkthroughs'
    | '/workshops/new'
    | '/workshops/$id/big-screen'
    | '/workshops'
    | '/workshops/$id/edit'
    | '/workshops/$id/manage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/_authenticated/coaches'
    | '/_authenticated/users'
    | '/_authenticated/walkthroughs'
    | '/_authenticated/workshops/new'
    | '/workshops/$id/big-screen'
    | '/_authenticated/workshops/'
    | '/_authenticated/workshops/$id/edit'
    | '/_authenticated/workshops/$id/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  WorkshopsIdBigScreenRoute: typeof WorkshopsIdBigScreenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coaches': {
      id: '/_authenticated/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof AuthenticatedCoachesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/walkthroughs': {
      id: '/_authenticated/walkthroughs'
      path: '/walkthroughs'
      fullPath: '/walkthroughs'
      preLoaderRoute: typeof AuthenticatedWalkthroughsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workshops/': {
      id: '/_authenticated/workshops/'
      path: '/workshops'
      fullPath: '/workshops/'
      preLoaderRoute: typeof AuthenticatedWorkshopsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workshops/new': {
      id: '/_authenticated/workshops/new'
      path: '/workshops/new'
      fullPath: '/workshops/new'
      preLoaderRoute: typeof AuthenticatedWorkshopsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/workshops/$id/big-screen': {
      id: '/workshops/$id/big-screen'
      path: '/workshops/$id/big-screen'
      fullPath: '/workshops/$id/big-screen'
      preLoaderRoute: typeof WorkshopsIdBigScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workshops/$id/edit': {
      id: '/_authenticated/workshops/$id/edit'
      path: '/workshops/$id/edit'
      fullPath: '/workshops/$id/edit'
      preLoaderRoute: typeof AuthenticatedWorkshopsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workshops/$id/manage': {
      id: '/_authenticated/workshops/$id/manage'
      path: '/workshops/$id/manage'
      fullPath: '/workshops/$id/manage'
      preLoaderRoute: typeof AuthenticatedWorkshopsIdManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCoachesRoute: typeof AuthenticatedCoachesRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWalkthroughsRoute: typeof AuthenticatedWalkthroughsRoute
  AuthenticatedWorkshopsNewRoute: typeof AuthenticatedWorkshopsNewRoute
  AuthenticatedWorkshopsIndexRoute: typeof AuthenticatedWorkshopsIndexRoute
  AuthenticatedWorkshopsIdEditRoute: typeof AuthenticatedWorkshopsIdEditRoute
  AuthenticatedWorkshopsIdManageRoute: typeof AuthenticatedWorkshopsIdManageRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCoachesRoute: AuthenticatedCoachesRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWalkthroughsRoute: AuthenticatedWalkthroughsRoute,
  AuthenticatedWorkshopsNewRoute: AuthenticatedWorkshopsNewRoute,
  AuthenticatedWorkshopsIndexRoute: AuthenticatedWorkshopsIndexRoute,
  AuthenticatedWorkshopsIdEditRoute: AuthenticatedWorkshopsIdEditRoute,
  AuthenticatedWorkshopsIdManageRoute: AuthenticatedWorkshopsIdManageRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  WorkshopsIdBigScreenRoute: WorkshopsIdBigScreenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
